import { Ingredient } from '@/types';

export const INGREDIENTS_DATA: Ingredient[] = [
  // Proteínas
  { id: '1',  name: 'pollo',          emoji: '🍗' },
  { id: '2',  name: 'carne molida',   emoji: '🥩' },
  { id: '3',  name: 'cerdo',          emoji: '🥩' },
  { id: '4',  name: 'res',            emoji: '🥩' },
  { id: '5',  name: 'salmón',         emoji: '🐟' },
  { id: '6',  name: 'atún',           emoji: '🐟' },
  { id: '7',  name: 'camarones',      emoji: '🍤' },
  { id: '8',  name: 'huevo',          emoji: '🥚' },
  { id: '9',  name: 'tofu',           emoji: '🍱' },
  { id: '10', name: 'tocino',         emoji: '🥓' },
  { id: '11', name: 'jamón',          emoji: '🍖' },
  { id: '12', name: 'salchicha',      emoji: '🌭' },
  { id: '13', name: 'chorizo',        emoji: '🥩' },
  { id: '14', name: 'pavo',           emoji: '🍗' },
  { id: '15', name: 'sardinas',       emoji: '🐟' },

  // Lácteos
  { id: '16', name: 'leche',          emoji: '🥛' },
  { id: '17', name: 'queso',          emoji: '🧀' },
  { id: '18', name: 'queso crema',    emoji: '🧀' },
  { id: '19', name: 'mantequilla',    emoji: '🧈' },
  { id: '20', name: 'crema',          emoji: '🥛' },
  { id: '21', name: 'yogur',          emoji: '🥛' },
  { id: '22', name: 'queso parmesano',emoji: '🧀' },
  { id: '23', name: 'queso mozzarella',emoji: '🧀' },

  // Cereales y harinas
  { id: '24', name: 'arroz',          emoji: '🍚' },
  { id: '25', name: 'pasta',          emoji: '🍝' },
  { id: '26', name: 'harina',         emoji: '🌾' },
  { id: '27', name: 'pan',            emoji: '🍞' },
  { id: '28', name: 'pan rallado',    emoji: '🍞' },
  { id: '29', name: 'avena',          emoji: '🌾' },
  { id: '30', name: 'maíz',          emoji: '🌽' },
  { id: '31', name: 'tortilla',       emoji: '🫓' },
  { id: '32', name: 'quinoa',         emoji: '🌾' },
  { id: '33', name: 'fideos',         emoji: '🍜' },

  // Verduras
  { id: '34', name: 'tomate',         emoji: '🍅' },
  { id: '35', name: 'cebolla',        emoji: '🧅' },
  { id: '36', name: 'ajo',            emoji: '🧄' },
  { id: '37', name: 'papa',           emoji: '🥔' },
  { id: '38', name: 'zanahoria',      emoji: '🥕' },
  { id: '39', name: 'pimiento',       emoji: '🫑' },
  { id: '40', name: 'espinaca',       emoji: '🥬' },
  { id: '41', name: 'lechuga',        emoji: '🥬' },
  { id: '42', name: 'brócoli',        emoji: '🥦' },
  { id: '43', name: 'calabacín',      emoji: '🥒' },
  { id: '44', name: 'berenjena',      emoji: '🍆' },
  { id: '45', name: 'champiñones',    emoji: '🍄' },
  { id: '46', name: 'apio',           emoji: '🥬' },
  { id: '47', name: 'pepino',         emoji: '🥒' },
  { id: '48', name: 'coliflor',       emoji: '🥦' },
  { id: '49', name: 'col',            emoji: '🥬' },
  { id: '50', name: 'acelga',         emoji: '🥬' },
  { id: '51', name: 'chícharos',      emoji: '🫛' },
  { id: '52', name: 'ejotes',         emoji: '🫛' },
  { id: '53', name: 'elote',          emoji: '🌽' },
  { id: '54', name: 'betabel',        emoji: '🫛' },
  { id: '55', name: 'puerro',         emoji: '🧅' },
  { id: '56', name: 'alcachofa',      emoji: '🥬' },
  { id: '57', name: 'espárragos',     emoji: '🌿' },
  { id: '58', name: 'chile',          emoji: '🌶️' },
  { id: '59', name: 'jalapeño',       emoji: '🌶️' },
  { id: '60', name: 'cebollín',       emoji: '🧅' },

  // Frutas
  { id: '61', name: 'limón',          emoji: '🍋' },
  { id: '62', name: 'naranja',        emoji: '🍊' },
  { id: '63', name: 'manzana',        emoji: '🍎' },
  { id: '64', name: 'plátano',        emoji: '🍌' },
  { id: '65', name: 'aguacate',       emoji: '🥑' },
  { id: '66', name: 'piña',           emoji: '🍍' },
  { id: '67', name: 'mango',          emoji: '🥭' },
  { id: '68', name: 'fresas',         emoji: '🍓' },
  { id: '69', name: 'uvas',           emoji: '🍇' },
  { id: '70', name: 'pera',           emoji: '🍐' },
  { id: '71', name: 'sandía',         emoji: '🍉' },
  { id: '72', name: 'melocotón',      emoji: '🍑' },
  { id: '73', name: 'cereza',         emoji: '🍒' },
  { id: '74', name: 'arándanos',      emoji: '🫐' },
  { id: '75', name: 'kiwi',           emoji: '🥝' },

  // Legumbres
  { id: '76', name: 'frijoles',       emoji: '🫘' },
  { id: '77', name: 'lentejas',       emoji: '🫘' },
  { id: '78', name: 'garbanzos',      emoji: '🫘' },
  { id: '79', name: 'habas',          emoji: '🫘' },

  // Aceites, salsas y condimentos
  { id: '80', name: 'aceite de oliva',emoji: '🫙' },
  { id: '81', name: 'aceite vegetal', emoji: '🫙' },
  { id: '82', name: 'salsa de tomate',emoji: '🍅' },
  { id: '83', name: 'salsa soya',     emoji: '🫙' },
  { id: '84', name: 'mayonesa',       emoji: '🫙' },
  { id: '85', name: 'mostaza',        emoji: '🌭' },
  { id: '86', name: 'ketchup',        emoji: '🍅' },
  { id: '87', name: 'salsa picante',  emoji: '🌶️' },
  { id: '88', name: 'vinagre',        emoji: '🫙' },
  { id: '89', name: 'aceite de sésamo',emoji: '🫙' },

  // Especias y hierbas
  { id: '90', name: 'sal',            emoji: '🧂' },
  { id: '91', name: 'pimienta',       emoji: '🧂' },
  { id: '92', name: 'comino',         emoji: '🌿' },
  { id: '93', name: 'paprika',        emoji: '🌶️' },
  { id: '94', name: 'orégano',        emoji: '🌿' },
  { id: '95', name: 'albahaca',       emoji: '🌿' },
  { id: '96', name: 'perejil',        emoji: '🌿' },
  { id: '97', name: 'cilantro',       emoji: '🌿' },
  { id: '98', name: 'tomillo',        emoji: '🌿' },
  { id: '99', name: 'romero',         emoji: '🌿' },
  { id: '100', name: 'laurel',        emoji: '🌿' },
  { id: '101', name: 'cúrcuma',       emoji: '🌿' },
  { id: '102', name: 'jengibre',      emoji: '🌿' },
  { id: '103', name: 'canela',        emoji: '🌿' },
  { id: '104', name: 'curry',         emoji: '🌿' },
  { id: '105', name: 'pimentón',      emoji: '🌶️' },

  // Frutos secos y semillas
  { id: '106', name: 'nueces',        emoji: '🥜' },
  { id: '107', name: 'almendras',     emoji: '🥜' },
  { id: '108', name: 'cacahuates',    emoji: '🥜' },
  { id: '109', name: 'semillas de sésamo', emoji: '🌰' },
  { id: '110', name: 'piñones',       emoji: '🌰' },
  { id: '111', name: 'avellanas',     emoji: '🥜' },
  { id: '112', name: 'semillas de girasol', emoji: '🌻' },

  // Repostería y dulces
  { id: '113', name: 'azúcar',        emoji: '🍬' },
  { id: '114', name: 'azúcar morena', emoji: '🍬' },
  { id: '115', name: 'miel',          emoji: '🍯' },
  { id: '116', name: 'chocolate',     emoji: '🍫' },
  { id: '117', name: 'cacao en polvo',emoji: '🍫' },
  { id: '118', name: 'vainilla',      emoji: '🌿' },
  { id: '119', name: 'polvo para hornear', emoji: '🌾' },
  { id: '120', name: 'levadura',      emoji: '🌾' },

  // Enlatados y conservas
  { id: '121', name: 'tomate en lata',emoji: '🥫' },
  { id: '122', name: 'atún en lata',  emoji: '🥫' },
  { id: '123', name: 'frijoles en lata', emoji: '🥫' },
  { id: '124', name: 'maíz en lata',  emoji: '🥫' },
  { id: '125', name: 'caldo de pollo',emoji: '🍲' },
  { id: '126', name: 'caldo de res',  emoji: '🍲' },
  { id: '127', name: 'caldo de verduras', emoji: '🍲' },

  // Bebidas y otros líquidos
  { id: '128', name: 'vino blanco',   emoji: '🍷' },
  { id: '129', name: 'vino tinto',    emoji: '🍷' },
  { id: '130', name: 'leche de coco', emoji: '🥥' },

  // Otros
  { id: '131', name: 'coco',          emoji: '🥥' },
  { id: '132', name: 'aceitunas',     emoji: '🫒' },
  { id: '133', name: 'alcaparras',    emoji: '🌿' },
  { id: '134', name: 'pepinillos',    emoji: '🥒' },
  { id: '135', name: 'pasta de tomate', emoji: '🍅' },
  { id: '136', name: 'crema agria',   emoji: '🥛' },
  { id: '137', name: 'fécula de maíz',emoji: '🌾' },
  { id: '138', name: 'arroz integral',emoji: '🍚' },
  { id: '139', name: 'pasta integral',emoji: '🍝' },
  { id: '140', name: 'pan pita',      emoji: '🫓' },
  { id: '141', name: 'hummus',        emoji: '🫘' },
  { id: '142', name: 'tahini',        emoji: '🫙' },
  { id: '143', name: 'miso',          emoji: '🫙' },
  { id: '144', name: 'salsa worcestershire', emoji: '🫙' },
  { id: '145', name: 'cebolla en polvo', emoji: '🧅' },
  { id: '146', name: 'ajo en polvo',  emoji: '🧄' },
  { id: '147', name: 'chili en polvo',emoji: '🌶️' },
  { id: '148', name: 'mezcla italiana', emoji: '🌿' },
  { id: '149', name: 'cebolla caramelizada', emoji: '🧅' },
  { id: '150', name: 'pasta de curry',emoji: '🌿' },
];
